// Ambiente do laboratório: App Service Plan Basic B1 (Windows) + Web App .NET 10 com as
// configurações do LabExternalId.Web. Escopo: resource group (criado uma vez, ver instrutor/provisionamento-actions.md).
targetScope = 'resourceGroup'

@description('Nome do Web App. Vira o hostname <nome>-<hash>.<regiao>-01.azurewebsites.net; precisa ser único.')
@minLength(2)
@maxLength(60)
param webAppName string

@description('Nome do App Service Plan.')
param planName string = 'plan-lab-externalid'

@description('Região dos recursos. Padrão: a região do resource group.')
param location string = resourceGroup().location

@description('Authority do tenant externo, no formato https://<subdominio>.ciamlogin.com/ (com barra final).')
param authority string = 'https://SEU-SUBDOMINIO.ciamlogin.com/'

@description('Application (client) ID do app registration LabExternalId-Web no tenant externo.')
param clientId string = 'SEU-CLIENT-ID'

@description('Client secret do app registration. Vazio = fluxo implícito de ID token (exige "ID tokens" marcado).')
@secure()
param clientSecret string = ''

@description('Tags aplicadas a todos os recursos.')
param tags object = {
  projeto: 'lab-entra-external-id'
  gerenciadoPor: 'github-actions'
}

resource plan 'Microsoft.Web/serverfarms@2024-04-01' = {
  name: planName
  location: location
  tags: tags
  kind: 'app'
  sku: {
    name: 'B1'
    tier: 'Basic'
    capacity: 1
  }
  properties: {
    reserved: false // Windows
  }
}

resource site 'Microsoft.Web/sites@2024-04-01' = {
  name: webAppName
  location: location
  tags: tags
  kind: 'app'
  properties: {
    serverFarmId: plan.id
    httpsOnly: true
    clientAffinityEnabled: false
    // Mesmo comportamento do portal: hostname <nome>-<hash>.<regiao>-01.azurewebsites.net. Só vale na criação.
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    siteConfig: {
      netFrameworkVersion: 'v10.0'
      alwaysOn: true
      http20Enabled: true
      minTlsVersion: '1.2'
      ftpsState: 'Disabled'
      metadata: [
        {
          name: 'CURRENT_STACK'
          value: 'dotnet'
        }
      ]
      appSettings: [
        {
          name: 'AzureAd__Authority'
          value: authority
        }
        {
          name: 'AzureAd__ClientId'
          value: clientId
        }
        {
          name: 'AzureAd__ClientSecret'
          value: clientSecret
        }
      ]
    }
  }
}

@description('Hostname padrão do Web App (com o sufixo único).')
output defaultHostName string = site.properties.defaultHostName

@description('URL base do app.')
output appUrl string = 'https://${site.properties.defaultHostName}'

@description('Redirect URIs a registrar no app registration LabExternalId-Web.')
output redirectUris array = [
  'https://${site.properties.defaultHostName}/signin-oidc'
  'https://${site.properties.defaultHostName}/signout-callback-oidc'
]

@description('Front-channel logout URL a registrar no app registration.')
output frontChannelLogoutUrl string = 'https://${site.properties.defaultHostName}/signout-oidc'
